version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package_customer.zip *.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_customer.zip s3://sales-incremental/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ecommerce-project-ci-cd --s3-bucket sales-incremental  --s3-key deployment_package_customer.zip
      - echo "Deployment complete!"
